language: php
dist: trusty
php:
- 5.5
- 5.6
- 7.0
- hhvm
- nightly
before_install:
- sudo apt-get update -qq
- sudo apt-get remove -y -qq --purge mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
- sudo apt-get install -y -qq mysql-server-5.6 mysql-client-5.6
matrix:
  allow_failures:
  - php: nightly
before_script: composer install
script: vendor/bin/phpunit
